- BusType:
  - name: bus1
    elements:
    - name: CANID_0x100
      dir: TX
      busElmTypeRef: BusElementQueueType/canDataQueue1
    - name: CANID_0x101
      dir: RX
      busElmTypeRef: BusElementQueueType/canDataQueue1
  - busName: bus2
    elements:
    - name: CANID_0x200
      dir: TX
      busElmTypeRef: BusElementQueueType/canDataQueue1
    - name: CANID_0x201
      dir: RX
      busElmTypeRef: BusElementQueueType/canDataQueue1

